version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - echo "Uploading frontend index.html to S3..."
      - aws s3 cp frontend/index.html s3://calculator-static-frontend-file-458284369197/index.html
artifacts:
  files: []
  discard-paths: yes
