AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for packaging Lambda

Parameters:
  ProjectName:
    Type: String
  DeploymentBucket:
    Type: String
  CodeBuildServiceRoleArn:
    Type: String
  LogProcessorLambdaArn:
    Type: String

Resources:
  LambdaBuild:
    Type: "AWS::Logs::LogGroup"
    Properties:
      RetentionInDays: 365
      LogGroupName: !Sub "code-build-lambda"
  LamdaDeploy:
    Type: "AWS::Logs::LogGroup"
    Properties:
      RetentionInDays: 365
      LogGroupName: !Sub "code-deploy-lambda"
  LambdaBuildSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Ref LogProcessorLambdaArn
      FilterPattern: ""
      LogGroupName: !Ref LambdaBuild

  LambdaDeploySubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Ref LogProcessorLambdaArn
      FilterPattern: ""
      LogGroupName: !Ref LamdaDeploy
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-Lambda-Build"
      ServiceRole: !Ref CodeBuildServiceRoleArn
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref LambdaBuild
          Status: "ENABLED"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 10

  LambdaDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-LambdaDeploy"
      Description: "CodeBuild project to deploy Lambda function"
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref LamdaDeploy
          Status: "ENABLED"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2

          phases:
            install:
              runtime-versions:
                nodejs: 22
            build:
              commands:
                - echo "Current working directory $(pwd)"
                - echo "Listing all files in current directory"
                - ls -al
                - LAMBDA_FUNCTION_NAME=calculator-Lambda
                - echo "Deploying Lambda function $LAMBDA_FUNCTION_NAME..."
                - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda.zip                   
          artifacts:
            files:
              - '**/*'
      Artifacts:
        Type: CODEPIPELINE              
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: PROJECT_NAME
            Value: !Ref ProjectName
      ServiceRole: !Ref CodeBuildServiceRoleArn
      

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject