AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda function deployment with API Gateway using Node.js 22

Parameters:
  ProjectName:
    Type: String
    Default: MyApp
    Description: Project name to prefix resources
  DeploymentBucket:
    Type: String
    Description: S3 bucket where CodeBuild uploads lambda.zip
    Default: "deployment-bucket"
  StageName:
    Type: String
    Default: dev
Resources:
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-ws-connections-458284369197"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-LambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: RealtimePushPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Allow scanning the connections table
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource: !GetAtt ConnectionsTable.Arn
              # Allow writing to CloudWatch logs (Lambda will have CloudWatch Basic via managed policy)
              - Effect: Allow
                Action:
                  - execute-api:ManageConnections
                Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*"


  ### WebSocket API (API Gateway v2) ###
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${ProjectName}-realtime-ws"
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  ConnectHandler:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-ws-connection-handler"
      Handler: index.handler
      Runtime: nodejs16.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          WS_API_ENDPOINT: !Sub "${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const ddb = new AWS.DynamoDB.DocumentClient();
          const TABLE = process.env.CONNECTIONS_TABLE;
          exports.handler = async (event) => {
            const route = event.requestContext.routeKey;
            const connectionId = event.requestContext.connectionId;
            if (route === '$connect') {
              await ddb.put({
                TableName: TABLE,
                Item: { connectionId }
              }).promise();
              return { statusCode: 200, body: 'connected' };
            } else if (route === '$disconnect') {
              await ddb.delete({
                TableName: TABLE,
                Key: { connectionId }
              }).promise();
              return { statusCode: 200, body: 'disconnected' };
            }
            return { statusCode: 200 };
          };
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectHandler.Arn}/invocations"
  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectHandler.Arn}/invocations"
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub "integrations/${ConnectIntegration}"
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub "integrations/${DisconnectIntegration}"
  ### Deployment & Stage ###
  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref WebSocketApi
    DependsOn:
      - ConnectRoute
      - DisconnectRoute

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: dev           # your stage name
      ApiId: !Ref WebSocketApi
      DeploymentId: !Ref WebSocketDeployment
      AutoDeploy: true
  LambdaPermissionForAPIGW:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ConnectHandler
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/${StageName}/$connect"
  LogProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-log-processor"
      Handler: index.handler
      Runtime: nodejs16.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          WS_API_ENDPOINT: !Sub "${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
      Code:
        ZipFile: |
          const zlib = require('zlib');
          const AWS = require('aws-sdk');
          const ddb = new AWS.DynamoDB.DocumentClient();
           const apiGateway = new AWS.ApiGatewayManagementApi({
              endpoint: process.env.WS_API_ENDPOINT
                        });

          const TABLE = process.env.CONNECTIONS_TABLE;

          exports.handler = async (event) => {
            // CloudWatch Logs subscription delivers base64 gzipped data in 'awslogs' property
            const payload = Buffer.from(event.awslogs.data, 'base64');
            const decompressed = zlib.gunzipSync(payload).toString('utf8');
            const parsed = JSON.parse(decompressed);
            const events = parsed.logEvents || [];

            // Build a simple broadcast message (you can extend this)
            for (const ev of events) {
              const message = {
                timestamp: parsed.logGroup ? parsed.logGroup : null,
                id: ev.id,
                message: ev.message
              };

              // Scan all connections and push (broadcast)
              let startKey = undefined;
              do {
                const res = await ddb.scan({
                  TableName: TABLE,
                  ExclusiveStartKey: startKey,
                  ProjectionExpression: "connectionId"
                }).promise();
                startKey = res.LastEvaluatedKey;

                const posts = res.Items.map(async (item) => {
                  try {
                    await apiGateway.postToConnection({
                      ConnectionId: item.connectionId,
                      Data: JSON.stringify(message)
                    }).promise();
                  } catch (err) {
                    // If connection is stale (410), remove from table
                    if (err.statusCode === 410) {
                      await ddb.delete({
                        TableName: TABLE,
                        Key: { connectionId: item.connectionId }
                      }).promise();
                    }
                  }
                });

                await Promise.all(posts);
              } while (startKey);
            }

            return { statusCode: 200 };
          };
  PermissionForLogsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LogProcessorLambda
      Action: lambda:InvokeFunction
      Principal: logs.amazonaws.com
  LambdaPermissionDisconnect:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ConnectHandler
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/${StageName}/$disconnect"
Outputs:
  WebSocketUrl:
    Description: WebSocket URL to use in the frontend (use wss://)
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"

  ConnectionsTableName:
    Description: DynamoDB table that stores connections
    Value: !Ref ConnectionsTable

  LogProcessorLambdaArn:
    Description: Lambda processing CloudWatch Logs and broadcasting
    Value: !GetAtt LogProcessorLambda.Arn
    Export:
      Name: !Sub "${ProjectName}-LogProcessorLambdaArn"